<?php

// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Zf3Php7Recaptcha\ReCaptcha'                => __DIR__.'/src/Zf3Php7Recaptcha/ReCaptcha.php',
    'Zf3Php7Recaptcha\Service\ReCaptchaService' => __DIR__.'/src/Zf3Php7Recaptcha/Service/ReCaptchaService.php',
    'Zf3Php7Recaptcha\Helper\ReCaptcha'         => __DIR__.'/src/Zf3Php7Recaptcha/Helper/ReCaptcha.php',
    'Zf3Php7Recaptcha\Module'                   => __DIR__.'/Module.php',
);
